# Generated by Django 4.0 on 2022-01-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('idaspirante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidopaterno', models.CharField(max_length=45)),
                ('apellidomaterno', models.CharField(max_length=45)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregunta', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Criterio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CursoPropedeutico',
            fields=[
                ('idcurso', models.AutoField(primary_key=True, serialize=False)),
                ('Clave', models.CharField(max_length=45)),
                ('FechaInicio', models.DateField()),
                ('FechaFinalizacion', models.DateField()),
                ('HoraInicio', models.TimeField()),
                ('HoraFinalizacion', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCriterioRubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.criterio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Respuesta', models.CharField(blank=True, max_length=150, null=True)),
                ('catalogopreguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.catalogopregunta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEntrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePonencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.criterio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.FileField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('observaciones', models.CharField(blank=True, max_length=85, null=True)),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('ApellidoPaterno', models.CharField(max_length=45)),
                ('ApellidoMaterno', models.CharField(max_length=45)),
                ('Curp', models.CharField(max_length=18, unique=True)),
                ('Rfc', models.CharField(max_length=13, unique=True)),
                ('CedulaProfesional', models.CharField(max_length=8, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusAspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusRequisitoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rubrica', models.CharField(max_length=50)),
                ('detallecriteriorubricas', models.ManyToManyField(through='CandidatosMaestria.DetalleCriterioRubrica', to='CandidatosMaestria.Criterio')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('descripcion', models.CharField(max_length=300)),
                ('detalle', models.ManyToManyField(through='CandidatosMaestria.DetalleRequisito', to='CandidatosMaestria.Aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHora', models.DateTimeField(blank=True, null=True)),
                ('Observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('detallePonencia', models.ManyToManyField(through='CandidatosMaestria.DetallePonencia', to='CandidatosMaestria.Criterio')),
                ('detalleentrevista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.detalleentrevista')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenSeneval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICNE', models.IntegerField()),
                ('PMA', models.IntegerField()),
                ('PAN', models.IntegerField()),
                ('ELE', models.IntegerField()),
                ('CLE', models.IntegerField()),
                ('MET', models.IntegerField()),
                ('ICL', models.IntegerField()),
                ('IUG', models.IntegerField()),
                ('aspirante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('HoraInicio', models.TimeField()),
                ('HoraFinal', models.TimeField()),
                ('Observaciones', models.CharField(blank=True, max_length=45, null=True)),
                ('DetalleEntrevista', models.ManyToManyField(through='CandidatosMaestria.DetalleEntrevista', to='CandidatosMaestria.Docente')),
                ('aspirante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaHora', models.DateTimeField(blank=True, null=True)),
                ('Observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('detalleEncuesta', models.ManyToManyField(through='CandidatosMaestria.DetalleEncuesta', to='CandidatosMaestria.CatalogoPregunta')),
                ('detalleentrevista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.detalleentrevista')),
            ],
        ),
        migrations.AddField(
            model_name='detallerequisito',
            name='estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.estatusrequisitoestudiante'),
        ),
        migrations.AddField(
            model_name='detallerequisito',
            name='requisito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.requisito'),
        ),
        migrations.AddField(
            model_name='detalleponencia',
            name='ponencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.ponencia'),
        ),
        migrations.AddField(
            model_name='detalleentrevista',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.docente'),
        ),
        migrations.AddField(
            model_name='detalleentrevista',
            name='entrevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.entrevista'),
        ),
        migrations.AddField(
            model_name='detalleencuesta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.encuesta'),
        ),
        migrations.AddField(
            model_name='detallecriteriorubrica',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.rubrica'),
        ),
        migrations.CreateModel(
            name='DetalleAspiranteCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Calificacion', models.IntegerField()),
                ('aspirante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.aspirante')),
                ('cursopropedeutico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.cursopropedeutico')),
            ],
        ),
        migrations.AddField(
            model_name='cursopropedeutico',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.docente'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='estatusaspirante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.estatusaspirante'),
        ),
    ]
