# Generated by Django 4.0 on 2022-01-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleaspirantecurso',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
