# Generated by Django 4.0 on 2022-01-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0002_alter_detalleaspirantecurso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleaspirantecurso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
