# Generated by Django 4.0 on 2022-01-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0003_alter_detalleaspirantecurso_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalleaspirantecurso',
            unique_together={('aspirante', 'cursopropedeutico')},
        ),
        migrations.AddIndex(
            model_name='detalleaspirantecurso',
            index=models.Index(fields=['aspirante', 'cursopropedeutico'], name='CandidatosM_aspiran_84bcb7_idx'),
        ),
    ]
