# Generated by Django 4.0 on 2022-01-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0004_alter_detalleaspirantecurso_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMaterias',
            fields=[
                ('idMateria', models.AutoField(primary_key=True, serialize=False)),
                ('Materia', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='cursopropedeutico',
            name='Clave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.catalogomaterias'),
        ),
    ]
