# Generated by Django 4.0 on 2022-01-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0005_catalogomaterias_alter_cursopropedeutico_clave'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detalleentrevista',
            unique_together={('entrevista', 'docente')},
        ),
        migrations.AddIndex(
            model_name='detalleentrevista',
            index=models.Index(fields=['entrevista', 'docente'], name='CandidatosM_entrevi_fc9882_idx'),
        ),
    ]
