# Generated by Django 4.0 on 2022-01-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0006_alter_detalleentrevista_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallecriteriorubrica',
            unique_together={('criterio', 'rubrica')},
        ),
        migrations.AddIndex(
            model_name='detallecriteriorubrica',
            index=models.Index(fields=['criterio', 'rubrica'], name='CandidatosM_criteri_4bde0a_idx'),
        ),
    ]
