# Generated by Django 4.0 on 2022-01-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0007_alter_detallecriteriorubrica_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleponencia',
            name='Valor',
            field=models.IntegerField(null=True),
        ),
    ]
