# Generated by Django 4.0 on 2022-01-14 05:15

import CandidatosMaestria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0008_detalleponencia_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequisito',
            name='carga',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisito',
            name='tamaño',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='detallerequisito',
            name='ruta',
            field=models.FileField(blank=True, null=True, upload_to=CandidatosMaestria.models.user_directory_path),
        ),
    ]
