# Generated by Django 4.0 on 2022-01-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0009_detallerequisito_carga_requisito_tamaño_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='tamaño',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
