# Generated by Django 4.0 on 2022-01-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0010_alter_requisito_tamaño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrevista',
            old_name='DetalleEntrevista',
            new_name='detalleentrevistas',
        ),
    ]
