# Generated by Django 4.0 on 2022-01-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0013_statusentrevista_encuesta_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.statusentrevista'),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.statusentrevista'),
        ),
    ]
