# Generated by Django 4.0 on 2022-01-27 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0014_alter_encuesta_status_alter_ponencia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='detalleentrevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.detalleentrevista', unique=True),
        ),
        migrations.AlterField(
            model_name='ponencia',
            name='detalleentrevista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.detalleentrevista', unique=True),
        ),
    ]
