# Generated by Django 4.0 on 2022-02-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0015_alter_encuesta_detalleentrevista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
            ],
        ),
    ]
