# Generated by Django 4.0 on 2022-02-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidatosMaestria', '0018_alter_aspirante_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidatosMaestria.periodo'),
        ),
    ]
