# Generated by Django 4.0 on 2022-01-07 05:24

import AlumnosMaestria.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidopaterno', models.CharField(max_length=45)),
                ('apellidomaterno', models.CharField(max_length=45)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('NumeroControl', models.IntegerField(unique=True)),
                ('Usuario', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.FileField(null=True, upload_to=AlumnosMaestria.models.user_directory_path)),
                ('observaciones', models.CharField(blank=True, max_length=95, null=True)),
                ('carga', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumnosMaestria.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='EstatusRequisitoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=600)),
                ('tamallo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('detalle', models.ManyToManyField(through='AlumnosMaestria.DetalleRequisito', to='AlumnosMaestria.Alumno')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumnosMaestria.semestre')),
            ],
        ),
        migrations.AddField(
            model_name='detallerequisito',
            name='estatusrequisitoalumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumnosMaestria.estatusrequisitoalumno'),
        ),
        migrations.AddField(
            model_name='detallerequisito',
            name='requisito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumnosMaestria.requisito'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='alumnosemestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumnosMaestria.semestre'),
        ),
    ]
